[phases.setup]
nixPkgs = [
  "php",
  "php83Extensions.gd",
  "php83Extensions.fileinfo"
]

[phases.install]
cmds = [
  "composer install --no-interaction --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"